//! Backend-neutral geometry generated by the Vita app layer.
//!
//! Pocket3D owns world rendering; OpenStrike owns the visual vocabulary for
//! bots, the rifle, tracers and impact sprites. Keeping these vertices free of
//! vita2d/vitaGL types makes the eventual Pocket3D Vita adapter a conversion
//! at one boundary instead of coupling simulation code to the GPU API.

#[cfg(target_os = "vita")]
use glam::Mat4;
use glam::Vec3;
use openstrike_core::weapon::{rifle_boxes, FxBeam, FxSprite, GUN_COLORS};
use openstrike_core::StrikeSim;
#[cfg(target_os = "vita")]
use pocket3d_vita::mesh::{
    clear_depth_for_viewmodel, draw_additive_tris, draw_color_tris, ColorVert,
};
#[cfg(target_os = "vita")]
use pocket3d_vita::FramePool;

#[cfg(target_os = "vita")]
pub type ColorVertex = ColorVert;

#[cfg(not(target_os = "vita"))]
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct ColorVertex {
    pub color: u32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
}

#[derive(Default)]
pub struct EffectGeometry {
    pub vertices: Vec<ColorVertex>,
    sprites: Vec<FxSprite>,
    beams: Vec<FxBeam>,
}

fn abgr(rgba: [u8; 4], brightness: f32) -> u32 {
    let channel = |value: u8| ((value as f32 * brightness).clamp(0.0, 255.0)) as u32;
    0xff00_0000 | (channel(rgba[2]) << 16) | (channel(rgba[1]) << 8) | channel(rgba[0])
}

fn abgr_f(color: [f32; 4]) -> u32 {
    let channel = |value: f32| (value.clamp(0.0, 1.0) * 255.0) as u32;
    (channel(color[3]) << 24)
        | (channel(color[2]) << 16)
        | (channel(color[1]) << 8)
        | channel(color[0])
}

fn vertex(position: Vec3, color: u32) -> ColorVertex {
    ColorVertex {
        color,
        x: position.x,
        y: position.y,
        z: position.z,
    }
}

fn add_quad(out: &mut Vec<ColorVertex>, corners: [Vec3; 4], color: u32) {
    out.extend_from_slice(&[
        vertex(corners[0], color),
        vertex(corners[1], color),
        vertex(corners[2], color),
        vertex(corners[0], color),
        vertex(corners[2], color),
        vertex(corners[3], color),
    ]);
}

fn add_box(out: &mut Vec<ColorVertex>, min: Vec3, max: Vec3, rgba: [u8; 4]) {
    let corner = |x: f32, y: f32, z: f32| Vec3 {
        x: if x > 0.0 { max.x } else { min.x },
        y: if y > 0.0 { max.y } else { min.y },
        z: if z > 0.0 { max.z } else { min.z },
    };
    let faces: [(f32, [Vec3; 4]); 6] = [
        (
            0.85,
            [
                corner(1.0, -1.0, 1.0),
                corner(1.0, -1.0, -1.0),
                corner(1.0, 1.0, -1.0),
                corner(1.0, 1.0, 1.0),
            ],
        ),
        (
            0.7,
            [
                corner(-1.0, -1.0, -1.0),
                corner(-1.0, -1.0, 1.0),
                corner(-1.0, 1.0, 1.0),
                corner(-1.0, 1.0, -1.0),
            ],
        ),
        (
            1.0,
            [
                corner(-1.0, 1.0, 1.0),
                corner(1.0, 1.0, 1.0),
                corner(1.0, 1.0, -1.0),
                corner(-1.0, 1.0, -1.0),
            ],
        ),
        (
            0.5,
            [
                corner(-1.0, -1.0, -1.0),
                corner(1.0, -1.0, -1.0),
                corner(1.0, -1.0, 1.0),
                corner(-1.0, -1.0, 1.0),
            ],
        ),
        (
            0.9,
            [
                corner(-1.0, -1.0, 1.0),
                corner(1.0, -1.0, 1.0),
                corner(1.0, 1.0, 1.0),
                corner(-1.0, 1.0, 1.0),
            ],
        ),
        (
            0.65,
            [
                corner(1.0, -1.0, -1.0),
                corner(-1.0, -1.0, -1.0),
                corner(-1.0, 1.0, -1.0),
                corner(1.0, 1.0, -1.0),
            ],
        ),
    ];
    for (brightness, corners) in faces {
        add_quad(out, corners, abgr(rgba, brightness));
    }
}

pub fn build_rifle() -> Vec<ColorVertex> {
    let mut vertices = Vec::new();
    for part in rifle_boxes() {
        add_box(&mut vertices, part.min, part.max, GUN_COLORS[part.color]);
    }
    vertices
}

/// Bot body in feet space (+Y up, facing -Z); the renderer applies each bot's
/// shared `transform_scaled(1.0)` matrix.
pub fn build_bot_body() -> Vec<ColorVertex> {
    const UNIFORM: [u8; 4] = [168, 142, 92, 255];
    const VEST: [u8; 4] = [70, 74, 62, 255];
    const SKIN: [u8; 4] = [206, 168, 130, 255];
    const GUNMETAL: [u8; 4] = [40, 40, 44, 255];
    let mut out = Vec::new();
    add_box(
        &mut out,
        Vec3::new(-11.0, 0.0, -6.0),
        Vec3::new(-2.0, 32.0, 6.0),
        UNIFORM,
    );
    add_box(
        &mut out,
        Vec3::new(2.0, 0.0, -6.0),
        Vec3::new(11.0, 32.0, 6.0),
        UNIFORM,
    );
    add_box(
        &mut out,
        Vec3::new(-13.0, 32.0, -7.0),
        Vec3::new(13.0, 54.0, 7.0),
        VEST,
    );
    add_box(
        &mut out,
        Vec3::new(-17.0, 34.0, -5.0),
        Vec3::new(-13.0, 52.0, 5.0),
        UNIFORM,
    );
    add_box(
        &mut out,
        Vec3::new(13.0, 34.0, -5.0),
        Vec3::new(17.0, 52.0, 5.0),
        UNIFORM,
    );
    add_box(
        &mut out,
        Vec3::new(-6.0, 54.0, -6.0),
        Vec3::new(6.0, 68.0, 6.0),
        SKIN,
    );
    add_box(
        &mut out,
        Vec3::new(-2.0, 40.0, -26.0),
        Vec3::new(2.0, 44.0, -4.0),
        GUNMETAL,
    );
    out
}

/// Build camera-facing quads for the current muzzle/tracer/impact effects.
pub fn build_effects(sim: &StrikeSim, camera_forward: Vec3) -> EffectGeometry {
    let mut geometry = EffectGeometry::default();
    build_effects_into(&mut geometry, sim, camera_forward);
    geometry
}

/// Like [`build_effects`], reusing the buffers retained in `out`.
pub fn build_effects_into(out: &mut EffectGeometry, sim: &StrikeSim, camera_forward: Vec3) {
    out.sprites.clear();
    out.beams.clear();
    sim.effects.emit(&mut out.sprites, &mut out.beams);
    let vertices = &mut out.vertices;
    vertices.clear();
    vertices.reserve((out.sprites.len() + out.beams.len()) * 6);

    let right = camera_forward.cross(Vec3::Y).normalize_or_zero();
    let up = right.cross(camera_forward);
    for sprite in &out.sprites {
        let radius_right = right * (sprite.size * 0.5);
        let radius_up = up * (sprite.size * 0.5);
        add_quad(
            vertices,
            [
                sprite.pos - radius_right - radius_up,
                sprite.pos + radius_right - radius_up,
                sprite.pos + radius_right + radius_up,
                sprite.pos - radius_right + radius_up,
            ],
            abgr_f(sprite.color),
        );
    }
    for beam in &out.beams {
        let side = (beam.b - beam.a).cross(camera_forward).normalize_or_zero() * (beam.width * 0.5);
        add_quad(
            vertices,
            [beam.a - side, beam.b - side, beam.b + side, beam.a + side],
            abgr_f(beam.color),
        );
    }
}

/// Queue every actor body using the shared simulation transform.
///
/// # Safety
///
/// A `pocket3d_vita` pass must be active and `pool` must remain stable until
/// `pocket3d_vita::end_3d` flushes it.
#[cfg(target_os = "vita")]
pub unsafe fn draw_bots(pool: &mut FramePool, body: &[ColorVertex], bots: &[openstrike_core::Bot]) {
    for bot in bots {
        unsafe { draw_color_tris(pool, body, bot.transform_scaled(1.0)) };
    }
}

/// Queue muzzle, tracer and impact geometry in world space.
///
/// # Safety
///
/// A `pocket3d_vita` pass must be active and `pool` must remain stable until
/// `pocket3d_vita::end_3d` flushes it.
#[cfg(target_os = "vita")]
pub unsafe fn draw_effects(
    pool: &mut FramePool,
    geometry: &mut EffectGeometry,
    sim: &StrikeSim,
    camera_forward: Vec3,
) {
    build_effects_into(geometry, sim, camera_forward);
    unsafe { draw_additive_tris(pool, &geometry.vertices, Mat4::IDENTITY) };
}

/// Queue the first-person rifle on a later painter layer so walls cannot
/// occlude it.
///
/// # Safety
///
/// A `pocket3d_vita` pass must be active and `pool` must remain stable until
/// `pocket3d_vita::end_3d` flushes it.
#[cfg(target_os = "vita")]
pub unsafe fn draw_viewmodel(pool: &mut FramePool, rifle: &[ColorVertex], sim: &StrikeSim) {
    if !sim.player.alive {
        return;
    }
    unsafe {
        clear_depth_for_viewmodel();
        draw_color_tris(pool, rifle, sim.viewmodel_transform_at(1.0));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn procedural_meshes_are_triangle_lists() {
        let rifle = build_rifle();
        let bot = build_bot_body();
        assert!(!rifle.is_empty());
        assert_eq!(rifle.len() % 3, 0);
        assert_eq!(bot.len(), 7 * 6 * 6);
    }

    #[test]
    fn effect_colors_keep_straight_alpha() {
        assert_eq!(abgr_f([1.0, 0.5, 0.25, 0.5]), 0x7f3f_7fff);
    }

    #[test]
    fn effect_scratch_buffers_are_reused_and_cleared() {
        let mut sim = StrikeSim::new(Vec3::ZERO, 0.0, Vec::new(), 0);
        sim.effects.spawn(
            openstrike_core::weapon::EffectKind::MuzzleFlash { pos: Vec3::ZERO },
            1.0,
        );
        sim.effects.spawn(
            openstrike_core::weapon::EffectKind::Tracer {
                a: Vec3::ZERO,
                b: Vec3::NEG_Z,
            },
            1.0,
        );
        let mut geometry = EffectGeometry::default();
        build_effects_into(&mut geometry, &sim, Vec3::NEG_Z);
        assert_eq!(geometry.vertices.len(), 12);
        assert_eq!(geometry.sprites.len(), 1);
        assert_eq!(geometry.beams.len(), 1);
        let pointers = (
            geometry.vertices.as_ptr(),
            geometry.sprites.as_ptr(),
            geometry.beams.as_ptr(),
        );
        let capacities = (
            geometry.vertices.capacity(),
            geometry.sprites.capacity(),
            geometry.beams.capacity(),
        );

        build_effects_into(&mut geometry, &sim, Vec3::NEG_Z);
        assert_eq!(
            pointers,
            (
                geometry.vertices.as_ptr(),
                geometry.sprites.as_ptr(),
                geometry.beams.as_ptr(),
            )
        );
        assert_eq!(
            capacities,
            (
                geometry.vertices.capacity(),
                geometry.sprites.capacity(),
                geometry.beams.capacity(),
            )
        );

        sim.effects.clear();
        build_effects_into(&mut geometry, &sim, Vec3::NEG_Z);
        assert!(geometry.vertices.is_empty());
        assert!(geometry.sprites.is_empty());
        assert!(geometry.beams.is_empty());
        assert_eq!(geometry.vertices.capacity(), capacities.0);
    }
}
