use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::PathBuf;

const MAP_COUNT: usize = 8;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=OPENSTRIKE_SYMBIAN_MAPS");
    println!("cargo:rerun-if-env-changed=OPENSTRIKE_SYMBIAN_DATA_ROOT");

    if env::var_os("CARGO_FEATURE_EMBEDDED_MAP_CATALOG").is_none() {
        return;
    }

    let names_source = required_env("OPENSTRIKE_SYMBIAN_MAPS");
    let names: Vec<&str> = names_source.split(',').collect();
    if names.len() != MAP_COUNT {
        panic!(
            "OPENSTRIKE_SYMBIAN_MAPS must contain exactly {MAP_COUNT} comma-separated map names"
        );
    }
    for name in &names {
        if !safe_map_name(name) {
            panic!(
                "OPENSTRIKE_SYMBIAN_MAPS contains unsafe name {name:?}; \
                 use lowercase ASCII letters, digits, '_' or '-'"
            );
        }
    }
    if names.windows(2).any(|pair| pair[0] >= pair[1]) {
        panic!("OPENSTRIKE_SYMBIAN_MAPS must be strictly sorted with no duplicates");
    }

    let root_source = required_env("OPENSTRIKE_SYMBIAN_DATA_ROOT");
    let root = root_source.trim_end_matches(['/', '\\']);
    if root.is_empty() || !root.is_ascii() || root.as_bytes().contains(&0) {
        panic!("OPENSTRIKE_SYMBIAN_DATA_ROOT must be a non-empty NUL-free ASCII path");
    }

    let mut generated = String::from(
        "// @generated by crates/openstrike-symbian/build.rs\n\
         pub(crate) static MAP_CATALOG: &[MapCatalogEntry] = &[\n",
    );
    for name in names {
        let path = format!("{root}/{name}.p3d\0");
        writeln!(
            generated,
            "    MapCatalogEntry {{ name: {name:?}, path: {} }},",
            rust_byte_string(path.as_bytes())
        )
        .expect("writing generated map catalogue");
    }
    generated.push_str("];\n");

    let output = PathBuf::from(required_env("OUT_DIR")).join("symbian_map_catalog.rs");
    fs::write(output, generated).expect("write generated Symbian map catalogue");
}

fn required_env(name: &str) -> String {
    env::var(name).unwrap_or_else(|_| panic!("{name} must be set for embedded-map-catalog"))
}

fn safe_map_name(name: &str) -> bool {
    !name.is_empty()
        && name.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_' || byte == b'-'
        })
}

fn rust_byte_string(bytes: &[u8]) -> String {
    let mut escaped = String::from("b\"");
    for &byte in bytes {
        match byte {
            b'\\' => escaped.push_str("\\\\"),
            b'"' => escaped.push_str("\\\""),
            b'\n' => escaped.push_str("\\n"),
            b'\r' => escaped.push_str("\\r"),
            b'\t' => escaped.push_str("\\t"),
            0 => escaped.push_str("\\0"),
            0x20..=0x7e => escaped.push(char::from(byte)),
            _ => write!(escaped, "\\x{byte:02x}").expect("writing byte escape"),
        }
    }
    escaped.push('"');
    escaped
}
